# GET ALL POSTS
GET http://localhost:5000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdF8zIiwiX2lkIjoiNjc0N2QwMmIxYjJmZDY2YjQ4NzIwN2RkIiwiaWF0IjoxNzMyNzU5ODUyLCJleHAiOjE3MzI3NTk5MDJ9.mMB3hYibBaehyH8rGTtEy7LCak8nDSGHbUbHhJodgSA

###

# GET ALL USERS
GET http://localhost:5000/user

###

# CREATE USER
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Dikshit_3",
    "password": "password"
}

###

# LOGIN
POST http://localhost:5001/auth/login
Content-Type: application/json

{
    "name": "Dikshit_3",
    "password": "password"
}

###

# TOKEN

GET http://localhost:5001/auth/token
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdF8zIiwiX2lkIjoiNjc0N2QwMmIxYjJmZDY2YjQ4NzIwN2RkIiwiaWF0IjoxNzMyNzU5NzMwfQ.e1NsBVsau4eDXYX3DpWkWf8vPsyynje4ZgggGsDznR4

###

# LOGOUT

DELETE http://localhost:5001/auth/logout
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdF8zIiwiX2lkIjoiNjc0N2QwMmIxYjJmZDY2YjQ4NzIwN2RkIiwiaWF0IjoxNzMyNzU5NzMwfQ.e1NsBVsau4eDXYX3DpWkWf8vPsyynje4ZgggGsDznR4"
}

###