# GET ALL POSTS
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdCIsInBhc3N3b3JkIjoiJDJiJDEwJE5WN0VucDg1Z0RmdDRSWW5ROXFoYk8wLm1wNWF6dkRXTDBYcUlTVWhZR2E0NEJ0NEoyWXFDIiwiaWF0IjoxNzMyMDk1NzU3LCJleHAiOjE3MzIwOTU4MDd9.lmsit0LX6ppPGwvJpkarnMx8yfArMM0GijTrsoTd0XA

###

# GET ALL USERS
GET http://localhost:5000/user

###

# CREATE USER
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Dikshit",
    "password": "password"
}

###

# LOGIN
POST http://localhost:5001/auth/login
Content-Type: application/json

{
    "name": "Dikshit",
    "password": "password"
}

###

# TOKEN

GET http://localhost:5001/auth/token
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdCIsInBhc3N3b3JkIjoiJDJiJDEwJE5WN0VucDg1Z0RmdDRSWW5ROXFoYk8wLm1wNWF6dkRXTDBYcUlTVWhZR2E0NEJ0NEoyWXFDIiwiaWF0IjoxNzMyMDk1NTc4fQ.sBEB6WG7aIV3lNu3ktHwwSsKeKTzQFrhGq8V3HHoEQc

###

# LOGOUT

DELETE http://localhost:5001/auth/logout
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGlrc2hpdCIsInBhc3N3b3JkIjoiJDJiJDEwJE5WN0VucDg1Z0RmdDRSWW5ROXFoYk8wLm1wNWF6dkRXTDBYcUlTVWhZR2E0NEJ0NEoyWXFDIiwiaWF0IjoxNzMyMDk1NTc4fQ.sBEB6WG7aIV3lNu3ktHwwSsKeKTzQFrhGq8V3HHoEQc"
}

###