GET http://localhost:5000/posts

###

GET http://localhost:5000/user

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Dikshit",
    "password": "password"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "Dikshit",
    "password": "password"
}

###